baseurl: ''
url: 'http://lab.diogorusso.com/time-property'
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - _assets
  - bower.json
  - Gemfile
  - Gemfile.lock
  - package.json
author: Diogo Russo
job: experience designer
title: Time Property
description: >-
  I'm a DESIGNER and STORYTELLER I help businesses, individuals and communities
  craft meaningful EXPERIENCES and PRODUCTS
logo: logo-v-white.svg
favico: /lib/img/_favicon.ico
avatar: +avatar.png
card: /lib/img/_site_card.jpg
email: your-email@domain.com
country: United States
region: California
city: Berkeley
collections:
  docs:
    output: true
description-PT: >-
  O Time Property é um conceito<br> que valoriza o seu bem mais precioso: o seu
  tempo livre.Com ele, você se torna membro<br> de um Club de luxo,<br>em um
  lugar paradisíaco,<br> para aproveitar<br> com a sua família e amigos.Tudo
  isso com uma<br> mensalidade a partir de R$ 248.
description-EN: >-
  Time Property is a concept that values your most precious asset: <br> your
  free time. With it, you become a member of a Luxury Club, in a heavenly place,
  to enjoy <br> with your family and friends.All with a monthly fee starting at
  R$ 248.
twitter_username: jekyllrb
github_username: jekyll
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page/default
      dev-info: true
      foundation5: 1
      fullpage: 1
      isotope: 1
      scroll-to: 1
      animation-page: 1
      animation-scroll: 1
      fitivid: 1
      swipebox: 1
      preloader: 1
      top-nav: 1
      footer: 2
      sidebar: 1
      grid: 1
      mast-head: 1
      back-to-top: 1
      map: 1
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      auto-scroll: false
      txt-color: dark
      hero: true
      hero-bg-color: '#000'
      title: TITLE DEFAULT
      cover: /lib/content/cover/post-default-cover.jpg
      description: DESCRIPTION DEFAULT
      tags:
        - journal
g-analytics: UA-59944728-3
fb-app-id: '915671155245552'
see-also:
  - 'http://work.diogorusso.com'
  - 'http://www.lucaszappa.com.br'
  - 'http://www.estudioberinjela.com.br'
social:
  - name: behance
    url: 'https://www.behance.net/diogorusso'
  - name: linkedin
    url: 'https://www.linkedin.com/in/diogorusso/en'
  - name: envelope-o
    url: 'mailto:contato@estudioberinjela.com.br'
